# Generated by Django 4.2.3 on 2024-06-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='image',
            field=models.ImageField(default='chais/', upload_to=''),
        ),
    ]
