# Generated by Django 4.2.3 on 2024-06-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0003_chaivariety_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='use',
            field=models.CharField(default='default_value', max_length=255),
        ),
    ]
