# Generated by Django 5.0.6 on 2024-07-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0007_chaicertificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaicertificate',
            name='certificate_number',
            field=models.CharField(max_length=255),
        ),
    ]
